title: "Carlos Villanueva Chavez"
author: "Carlos Villanueva Chavez"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "https://carlos91016.github.io/carlos-cv/"}
  - {title: "Research", file: "research.md"}
  - {title: "Projects"}
  - {title: "Blog", file: "blog.md"}
  - {title: "Personal", file: "personal.md"}
  
  #- {file: "index.html"}
  #- {file: "README.md", title: "About me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:carlosvch@ou.edu"}
  - {title: Github, icon: github, url: "https://github.com/Carlos91016"}
  - {title: Facebook, icon: facebook, url: "https://www.facebook.com/carlos.villanuevachavez.1"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/carlosvillchz/"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
